services:
  - type: web
    name: requisicao-projec     # vocÃª pode mudar aqui
    env: python
    plan: free

    buildCommand: "pip install -r requirements.txt"

    startCommand: "python manage.py migrate && gunicorn requisicoes.wsgi:application"

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
