services:
  - type: web
    name: requisicao-projec
    runtime: python
    plan: free

    buildCommand: "pip install -r requirements.txt"

    startCommand: "./entrypoint.sh"

    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
