services:
  - type: web
    name: reque
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn requisicoes.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
